### ISSUE TITLE
Chrome Driver Path not working

### ISSUE THREAD

**Issue by Muscan** [coding-with-dom/intro-to-nightwatchjs#1]
Hi. 
In the nightwatch.conf.js at the line 9 you have
server_path': 'node_modules/.bin/chromedriver'.
 Well, after investigating it, I found a solution which worked for me. 
'server_path': 'node_modules/chromedriver/lib/chromedriver/chromedriver.exe'

Thanks!
Muscan

**Comment by aberonni** [comment]
Thanks for pointing this out! Indeed, the code I was using is not valid on windows which is why it wasn't working for you. I've pushed a fix (you can see the link to it above) which should now make it work on all platforms.
